algoritmo "Exercícios da aula 6"
// Função : Calcula a área de um triângulo
// Autor :  Hamilton R. Tabosa
// Data : 08/04/2020

// Seção de Declarações
var
base, altura, area: real
inicio
// Seção de Comandos
Escreval("Qual a medida da base do triângulo?")
Leia(base)
Escreval("Qual a medida da altura do triângulo?")
Leia(altura)
area<- (base * altura / 2)
Escreva("A área do triângulo é", area)
fimalgoritmo
