algoritmo "Exercícios da aula 5"
// Função : Mostra a soma e a subtração de dois números
// Autor :  Hamilton R. Tabosa
// Data : 01/04/2020

// Seção de Declarações 
var
n1, n2, anodenascimento: inteiro
inicio
// Seção de Comandos 
Escreval("Digite o ano atual:")
Leia(n1)
Escreval("Qual a sua idade em anos?")
Leia(n2)
anodenascimento<- (n1 - n2)
Escreva("Desconsiderando o mês de nascimento, você provavelmente nasceu em", anodenascimento)
fimalgoritmo
