algoritmo "Exercícios da aula 5"
// Função : Calcula o comprimento de uma circunferência
// Autor :  Hamilton R. Tabosa
// Data : 01/04/2020

// Seção de Declarações 
var
raio, comprimento: real
inicio
// Seção de Comandos 
Escreval("Digite o raio da circunferência:")
Leia(raio)
pi<- (3.14)
comprimento<- (2 * 3.14 * raio)
Escreva("O comprimento da circunferência com raio", raio, " é: ", comprimento)
fimalgoritmo
