algoritmo "Exercício da Aula 6"
// Função :   Converte de Real para Dólar e Euro
// Autor :    Hamilton R. Tabosa
// Data : 08/04/2020
// Seção de Declarações 
var
valorR, valorD, valorE: Real

inicio
// Seção de Comandos
Escreval("Qual o valor em Reais?")
Leia(valorR)
valorD<- (valorR * 0.19)
valorE<- (valorR * 0.18)

Escreva(valorR, " Reais equivale a", valorD, " Dólares e a ", valorE, " Euros. Cotação válida para o dia 08/04/2020.")
fimalgoritmo
fimalgoritmo
