algoritmo "Exercícios da aula 5"
// Função : Mostra a soma e a subtração de dois números
// Autor :  Hamilton R. Tabosa
// Data : 01/04/2020

// Seção de Declarações 
var
n1, n2, soma, subtracao: inteiro
inicio
// Seção de Comandos 
Escreval("Digite o primeiro número:")
Leia(n1)
Escreval("Digite o segundo número:")
Leia(n2)
Soma<- (n1 + n2)
Subtracao<- (n1 - n2)
Escreva("A soma dos dois números é ",soma, " e a direfença entre eles é ", subtracao)
fimalgoritmo
